######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 17 21:43:19 2012
######################################################################

TEMPLATE = app
TARGET = quiche-processmanager
DEPENDPATH += .
INCLUDEPATH += .

QT = core

# Input
HEADERS += process.h processmanager.h
SOURCES += main.cpp process.cpp processmanager.cpp

linux-rasp-pi-g++{
    target.path = /usr/bin
}

INSTALLS += target
